'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tcProduct
    Public Property Id As Integer
    Public Property Name As String
    Public Property Cost As Nullable(Of Decimal)
    Public Property Price As Nullable(Of Decimal)
    Public Property Stock As Nullable(Of Integer)

End Class
