'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tcPurchas
    Public Property Id As Integer
    Public Property ProductId As String
    Public Property Quantity As Nullable(Of Integer)
    Public Property Cost As Nullable(Of Decimal)
    Public Property PruchaseId As Nullable(Of Integer)

End Class
