'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tcServiceSell
    Public Property Id As Integer
    Public Property ServiceId As Nullable(Of Integer)
    Public Property Quantity As Nullable(Of Integer)
    Public Property Price As Nullable(Of Decimal)
    Public Property BillId As Nullable(Of Integer)

End Class
