'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TCESbaseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TCESbaseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tcBills() As DbSet(Of tcBill)
    Public Overridable Property tcClients() As DbSet(Of tcClient)
    Public Overridable Property tcExpenses() As DbSet(Of tcExpens)
    Public Overridable Property tcGroups() As DbSet(Of tcGroup)
    Public Overridable Property tcProducts() As DbSet(Of tcProduct)
    Public Overridable Property tcProductSells() As DbSet(Of tcProductSell)
    Public Overridable Property tcPurchaseCorrelatives() As DbSet(Of tcPurchaseCorrelative)
    Public Overridable Property tcPurchases() As DbSet(Of tcPurchas)
    Public Overridable Property tcServices() As DbSet(Of tcService)
    Public Overridable Property tcServiceSells() As DbSet(Of tcServiceSell)
    Public Overridable Property tcUsers() As DbSet(Of tcUser)

End Class
