//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderOnlineModule.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZionEntities : DbContext
    {
        public ZionEntities()
            : base("name=ZionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tcBill> tcBills { get; set; }
        public virtual DbSet<tcClient> tcClients { get; set; }
        public virtual DbSet<tcExpense> tcExpenses { get; set; }
        public virtual DbSet<tcGroup> tcGroups { get; set; }
        public virtual DbSet<tcProduct> tcProducts { get; set; }
        public virtual DbSet<tcProductSale> tcProductSales { get; set; }
        public virtual DbSet<tcPurchaseCorrelative> tcPurchaseCorrelatives { get; set; }
        public virtual DbSet<tcPurchas> tcPurchases { get; set; }
        public virtual DbSet<tcService> tcServices { get; set; }
        public virtual DbSet<tcServiceSale> tcServiceSales { get; set; }
        public virtual DbSet<tcUser> tcUsers { get; set; }
        public virtual DbSet<tcClientDetail> tcClientDetails { get; set; }
    }
}
